---
# Trivy configuration for IaC scanning
# See https://aquasecurity.github.io/trivy/latest/docs/references/configuration/

# Scan settings
scan:
  # Skip files and directories
  skip-dirs:
    - .git
    - .github
    - .terraform
    - .node_modules
    - .venv
    - .ansible
    - .vscode

  skip-files:
    - "**/*.md"
    - "**/.gitignore"

# Severity levels to report
severity:
  - CRITICAL
  - HIGH
  - MEDIUM

# Vulnerability settings
vulnerability:
  type:
    - os
    - library

# Misconfiguration settings
misconfiguration:
  # Scan for misconfigurations
  enabled: true

  # IaC types to scan
  scanners:
    - terraform
    - cloudformation
    - dockerfile
    - kubernetes

  # Policy settings
  policy:
    # Use built-in policies
    namespaces:
      - builtin.terraform.aws
      - builtin.terraform.azure
      - builtin.terraform.gcp
      - builtin.dockerfile
      - builtin.kubernetes

# Secret scanning
secret:
  enabled: true

# License scanning (optional)
license:
  enabled: false

# Output format
format: table

# Exit code
# 0: no vulnerabilities found
# 1: vulnerabilities found
exit-code: 1

# Ignore unfixed vulnerabilities
ignore-unfixed: false

# Timeout for scan
timeout: 5m

# Cache settings
cache:
  # Cache directory
  dir: ~/.cache/trivy

# Skip checks by ID
skip-policy-update: false
# Custom checks to skip (examples)
# skip-checks:
#   - AVD-AWS-0001  # Example: Skip specific AWS check
#   - AVD-AZR-0001  # Example: Skip specific Azure check
#   - AVD-GCP-0001  # Example: Skip specific GCP check
