---
extends: default

rules:
  # Indentation is critical for IaC
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: true

  # Required by ansible-lint
  comments-indentation: false
  comments:
    min-spaces-from-content: 1

  # Required by ansible-lint production rules
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true

  # Allow long lines (URLs, commands, cloud-init, Terraform)
  line-length:
    max: 200
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  # Avoid trailing spaces
  trailing-spaces: { level: warning }

  # No multiple consecutive blank lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

ignore: |
  .git/
  .github/
  venv/
  .cache/
  .tox/
  node_modules/
  .terraform/
  terraform/
  packer/
